                    

                    
MAX_ARTICLES_PER_SOURCE = 10
TAVILY_DAYS_BACK = 7
HACKER_NEWS_DAYS_BACK = 3
ARXIV_MAX_RESULTS = 10
RSS_MAX_RESULTS_PER_FEED = 3

                 
MAX_ARTICLES_TO_ANALYZE = 14
TARGET_FINAL_ARTICLES = 10
MIN_TREND_SCORE = 1.0

                   
MAX_CONTENT_LENGTH = 2500
MAX_OUTPUT_TOKENS = 1024
RETRY_DELAY_SECONDS = 8
MAX_RETRIES = 5
ANALYSIS_THROTTLE_SECONDS = 3

                    
MIN_SUMMARY_WORDS = 10
