# config/settings.py

# Retriever Settings
MAX_ARTICLES_PER_SOURCE = 10
TAVILY_DAYS_BACK = 7
GITHUB_DAYS_BACK = 14

# Ranker Settings
MAX_ARTICLES_TO_ANALYZE = 15
TARGET_FINAL_ARTICLES = 10
MIN_TREND_SCORE = 1.5

# Analyzer Settings
MAX_CONTENT_LENGTH = 12000
MAX_OUTPUT_TOKENS = 1024
RETRY_DELAY_SECONDS = 8
MAX_RETRIES = 5
ANALYSIS_THROTTLE_SECONDS = 2

# Evaluator Settings
MIN_SUMMARY_WORDS = 10
